services:
  headscale:
    image: headscale/headscale:0.25.1
    restart: unless-stopped
    container_name: headscale
    ports:
      #- "0.0.0.0:8080:8080"
      - "127.0.0.1:9090:9090"
    volumes:
      # - ./headscale/config:/etc/headscale
      # - ./headscale/data:/var/lib/headscale
      - ./headscale:/etc/headscale
      - headscale_data:/var/lib/headscale
    command: serve
    networks:
      - caddy_nw

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    networks:
      - caddy_nw

  caddy:
    image: caddy
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - caddy_nw
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  headscale_data:

networks:
  caddy_nw:
    # internal: true
