services:
  # headscale:
  #   image: headscale/headscale:0.25.1
  #   restart: unless-stopped
  #   container_name: headscale
  #   ports:
  #     - "9090:9090"
  #   expose:
  #     - "8080"
  #   volumes:
  #     - ./headscale/config:/etc/headscale  # Configuration files
  #     - ./headscale/data:/var/lib/headscale # Data persistence
  #   command: serve
  #   networks:
  #     - headscale-proxied_default
  #   depends_on:
  #     - nginx-proxy-manager

  caddy:
    image: caddy
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - caddy-net
    volumes:
      - ./caddy/data/:/data/
      - ./caddy/config/:/config/
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
