services:
  headscale:
    image: headscale/headscale:0.25.1
    restart: unless-stopped
    container_name: headscale
    ports:
      #- "0.0.0.0:8080:8080"
      - "127.0.0.1:9090:9090"
    volumes:
      - ./headscale/config:/etc/headscale
  #     - ./headscale/data:/var/lib/headscale # Data persistence
      - caddy_data:/etc
    command: serve
    networks:
      caddy-net:
  
  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    networks:
      caddy-net:

  caddy:
    image: caddy
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - caddy-net
    volumes:
      - ./caddy/data/:/data/
      - ./caddy/config/:/config/
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  caddy-net:
    external: true

volumes:
  caddy_data:
    external: true
